spring.application.name=FashionShop

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=fashion_shop;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.mvc.static-path-pattern=/images/**
spring.web.resources.static-locations=file:images/

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

spring.security.oauth2.client.registration.google.client-id=662047655985-itsivnv7ok9cquob68jvi1705kjsnudu.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
