spring.application.name=FashionShop

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=fashion_shop;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8
spring.datasource.username=sa
spring.datasource.password=123456
	
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.mvc.static-path-pattern=/images/**
spring.web.resources.static-locations=file:images/

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
