spring.application.name=FashionShop

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=fashion_shop;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.mvc.static-path-pattern=/images/**
spring.web.resources.static-locations=file:images/

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

spring.profiles.active=dev
ghn.api.token=6547191c-7ccd-11f0-873d-ee33b76c5ced
ghn.api.shop-id=197297
ghn.api.from-district-id=3317
ghn.api.shop-phone=0817715339
ghn.api.url=https://dev-online-gateway.ghn.vn/shiip/public-api/v2


